[package]
name = "ttcp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
byteorder = "1.5.0"
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3"